services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: requirements/nginx/
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    env_file:
      - .env
    secrets:
      - ssl_crt
      - ssl_key
    ports:
      - "443:443"
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context:  requirements/mariadb/
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - wp_password
      - wp_admin_password
      - db_password
      - db_root_password
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: requirements/wordpress/
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - wp_password
      - wp_admin_password
      - db_password
      - db_root_password
    restart: always

networks:
  inception:
    name: inception

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: "${HOME}/data/mariadb"
      o: bind
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: "${HOME}/data/wordpress"
      o: bind

secrets:
  ssl_crt:
    file: ../secrets/ssl_certificate
  ssl_key:
    file: ../secrets/ssl_certificate_key
  db_password:
    file: ../secrets/db_password
  db_root_password:
    file: ../secrets/db_root_password
  wp_password:
    file: ../secrets/wp_password
  wp_admin_password:
    file: ../secrets/wp_admin_password